config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'products#index'


  devise_for :admins
  devise_for :users



  resources :amenities

  get 'carts/order'
  post 'carts/finalize'
  resource :carts, only: [:show]

  resources :categories

  resources :order_items, only: [:create, :update, :destroy]

  resources :orders

  resources :platforms

  get 'products/shop'
  resources :products

  resources :shippings

  get 'users/:id/edit_address', to: 'users#edit_address', as: 'users_edit_address'
  resources :users
  resources :admins


end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_confirmation_of :password
  serialize :amenities, JSON
end

app/models/amenity.rb
class Amenity < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :products
end

app/models/order.rb
class Order < ApplicationRecord

  has_many :order_items
  before_create :set_order_params
  belongs_to :shipping, optional: true
  belongs_to :order_status, optional: true
  belongs_to :user, optional: true

private

  def set_order_params
    # self.order_status_id = OrderStatus.find_by(name: 'Stan tymczasowy').id
    # self.shipping_id = Shipping.find_by(name: 'Stan tymczasowy').id
  end

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :product_present
  validate :order_present

  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price-(product.price*(product.discount.to_f / 100 ))
    end
  end

private
  def product_present
    if product.nil?
      errors.add(:product, "is not valid or is not active.")
    end
  end

  def order_present
    if order.nil?
      errors.add(:order, "is not a valid order.")
    end
  end

  def finalize
    self[:unit_price] = unit_price
  end

end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
	has_many :orders
end

app/models/platform.rb
class Platform < ApplicationRecord
  has_many :products
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  belongs_to :platform
  has_many :order_items

  mount_uploaders :picture, PictureUploader
  serialize :picture, JSON
end

app/models/shipping.rb
class Shipping < ApplicationRecord
  has_many :orders
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/amenities_helper.rb
module AmenitiesHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/platforms_helper.rb
module PlatformsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/shippings_helper.rb
module ShippingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/_form.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <%= form_for(admin) do |f| %>
      <% if admin.errors.any? %>
        <div id="error_explanation">
          <h2>Zmiany nie mogą zostać zapisane:</h2>

          <ul>
            <% admin.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= f.label :email %><br/>
        <%= f.email_field :email, autofocus: true, class:'form-control', placeholder:'podaj email' %>
      </div>

      <div class="form-group">
        <%= f.label 'Uprawnienia' %>
        <%= f.collection_select(:amenities, Amenity.all, :name, :name, {include_blank: true, include_hidden: false}, { multiple: true, class: 'form-control'}) %>
      </div>


      <div class="form-group">
        <%= check_box_tag 'form_dis' %>
        <%= f.label 'label', 'Zmień hasło',class: 'control-label' %></br>
        <%= f.label 'Hasło' %>
        <%= f.password_field :password, autocomplete: "off", class: 'form-control', placeholder:'podaj hasło', disabled: 'disabled' %>
      </div>

      <div class="form-group">
        <%= f.label 'Potwierdź Hasło' %>
        <%= f.password_field :password_confirmation, autocomplete: "off", class: 'form-control', placeholder:'potwierdź hasło', disabled: 'disabled' %>
      </div>

      <div class="form-group">
        <%= f.submit 'Zapisz', class:'btn btn-primary btn-block' %>
      </div>
    <% end %>

    <script type="text/javascript" charset="utf-8">
        $('#form_dis').on('click', function(){
            if($(this).prop('checked')){
                $('#admin_password').removeAttr('disabled');
                $('#admin_password_confirmation').removeAttr('disabled');
            } else {
                $('#admin_password').attr('disabled', 'disabled');
                $('#admin_password_confirmation').attr('disabled', 'disabled');
            }
        })
    </script>
  </div>
</div>

app/views/admins/edit.html.erb
<div class="row">
  <div class="col-md-12">
    <h1>Edytowanie Administratora</h1>

    <%= render 'form', admin: @admin %>

    <%= link_to 'Podgląd', @admin, class: 'btn btn-default' %> |
    <%= link_to 'Wstecz', admins_path, class: 'btn btn-default' %>
  </div>
</div>

app/views/admins/index.html.erb
<div class="row">
  <div class="col-md-12">
    <h1>Administratorzy</h1>

    <table class="table table-bordered table-condensed table-striped">
      <thead>
        <tr>
          <th>Email</th>
          <th>Uprawnienia</th>
          <th>Narzędzia</th>
        </tr>
      </thead>

      <tbody>
        <% @admins.each do |admin| %>
          <tr>
            <td><%= admin.email %></td>
            <td>
              <% admin.amenities.as_json.each do |f| %>
                  <%= f %> <br/>
              <% end %>
            </td>
            <td>
              <ul class="list-inline">
                <li>
                  <%= link_to admin do %>
                      <%= fa_icon 'eye', style: 'color: black' %> Podgląd
                  <% end %>
                </li>

                <li>
                  <%= link_to edit_admin_path admin do %>
                      <%= fa_icon 'pencil', style: 'color: black' %> Edycja
                  <% end %>
                </li>

                <li>
                  <%= link_to admin, method: :delete, data: {confirm: 'Jesteś pewien?'} do %>
                      <%= fa_icon 'times', style: 'color: black' %> Usuń
                  <% end %>
                </li>
              </ul>
            </td>

          </tr>
        <% end %>
      </tbody>
    </table>
    <%= link_to new_admin_path, class: 'btn btn-default' do %>
        <%= fa_icon('plus') %>  Nowy Administrator
    <% end %>
  </div>
</div>

app/views/admins/new.html.erb
<div class="row">
  <div class="col-md-12">
    <h1>Nowy Administrator</h1>

<%= render 'form', admin: @admin %>

    <%= link_to 'Wstecz', admins_path, class: 'btn btn-default' %>
  </div>
</div>

app/views/admins/show.html.erb
<div class="row">
  <div class="col-md-12">
    <p>
      <strong>Email:</strong>
      <%= @admin.email %>
    </p>
    <p>
      <strong>Uprawnienia:</strong>
      <% @admin.amenities.as_json.each do |f| %>
          <%= f %>,
      <% end %>
    </p>
    <%= link_to 'Edytuj', edit_admin_path(@admin), class: 'btn btn-default' %> |
    <%= link_to 'Wstecz', admins_path, class: 'btn btn-default' %>
  </div>
</div>

app/views/layouts/_cart_text.html.erb
<%= link_to carts_path do %>
    <%= fa_icon('shopping-cart') %>
    <span class="label label-as-badge
      <% if current_order.order_items.size == 0 %>
      label-default
      <% else %>
      label-success
      <% end %>
    ">
    <%= "#{current_order.order_items.size}" %></span> Koszyk

<% end %>

app/views/layouts/_nav.html.erb
<div class="navbar navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <% if signed_in? %>
          <% if user_signed_in? %>
              <li class="<%= 'active' if params[:controller] == 'products' %>"><%= link_to 'Produkty', products_path %></li>
          <% end %><!-- /user -->

          <% if admin_signed_in? %>
            <% if have 'Kategorie'  %>
              <li class="<%= 'active' if params[:controller] == 'categories' %>"><%= link_to('Kategorie', categories_path)  %></li>
            <% end %>

            <% if have 'Zamówienia' %>
              <li class="<%= 'active' if params[:controller] == 'orders' %>"><%= link_to('Zamówienia', orders_path)  %></li>
            <% end %>

            <% if have 'Kategorie' %>
              <li class="<%= 'active' if params[:controller] == 'platforms' %>"><%= link_to('Platformy', platforms_path)  %></li>
            <% end %>

            <% if have 'Kategorie' %>
              <li class="<%= 'active' if params[:controller] == 'shippings' %>"><%= link_to('Rodzaje Dostawy', shippings_path)  %></li>
            <% end %>

            <% if have 'Magazyn' %>
              <li class="<%= 'active' if params[:controller] == 'products' %>"><%= link_to('Produkty', products_path)  %></li>
            <% end %>

            <% if have 'Super Admin' %>
              <li class="<%= 'active' if params[:controller] == 'amenities' %>"><%= link_to('Uprawnienia', amenities_path)  %></li>
            <% end %>

            <% if have 'Super Admin' %>
              <li class="<%= 'active' if params[:controller] == 'admins' %>"><%= link_to('Administratorzy', admins_path)  %></li>
            <% end %>
          <% end %><!-- /admin -->
          <% else %>
          <li class="<%= 'active' if params[:controller] == 'products' %>"><%= link_to 'Produkty', products_path %></li>
        <% end %>
      </ul><!-- /.navbar-left -->

      <ul class="nav navbar-nav navbar-right">
        <% if signed_in? %>
          <% if user_signed_in? %>
            <li class="cart-text"><%= render 'layouts/cart_text' %></li>
            <li class="<%= 'active' if params[:controller] == 'users'  %>"><%= link_to('Profil', current_user) %></li>
            <li><%= link_to('Wyloguj', destroy_user_session_path, :method => :delete) %></li>
          <% end %><!-- /user -->

          <% if admin_signed_in? %>
            <li><%= link_to('Wyloguj', destroy_admin_session_path, :method => :delete) %></li>
          <% end %><!-- /admin -->

          <% else %>
            <li class="cart-text"><%= render 'layouts/cart_text' %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Zaloguj <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to('Zaloguj jako Użytkownik', new_user_session_path)  %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to('Zaloguj jako Admin', new_admin_session_path)  %></li>
              </ul>
            </li>
        <% end %>
      </ul><!-- /.navbar-right -->
    </div><!-- /.nav-collapse -->
  </div><!-- /.container -->
</div><!-- /.navbar -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <title>Agile</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render "layouts/nav" %>

  <div class="container">
    <% if notice or alert %>
      <div class="row notification">
        <div class="col-md-12">
          <% if notice %>
          <p class="alert alert-success"><%= notice %></p>
          <% end %>
          <% if alert %>
          <p class="alert alert-danger"><%= alert %></p>
          <% end %>
        </div>
      </div>
    <% end %>

      <%= yield %>

    </div>

  <footer>© Copyright 2017</footer>

  </body>

</html>