config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'products#index'


  devise_for :admins
  devise_for :users



  resources :amenities

  get 'carts/order'
  post 'carts/finalize'
  resource :carts, only: [:show]

  resources :categories

  resources :order_items, only: [:create, :update, :destroy]

  resources :orders

  resources :platforms

  get 'products/shop'
  resources :products

  resources :shippings

  get 'users/:id/edit_address', to: 'users#edit_address', as: 'users_edit_address'
  resources :users
  resources :admins


end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_confirmation_of :password
  serialize :amenities, JSON
end

app/models/amenity.rb
class Amenity < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :products
end

app/models/order.rb
class Order < ApplicationRecord

  has_many :order_items
  before_create :set_order_params
  belongs_to :shipping, optional: true
  belongs_to :order_status, optional: true
  belongs_to :user, optional: true

private

  def set_order_params
    # self.order_status_id = OrderStatus.find_by(name: 'Stan tymczasowy').id
    # self.shipping_id = Shipping.find_by(name: 'Stan tymczasowy').id
  end

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :product_present
  validate :order_present

  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price-(product.price*(product.discount.to_f / 100 ))
    end
  end

private
  def product_present
    if product.nil?
      errors.add(:product, "is not valid or is not active.")
    end
  end

  def order_present
    if order.nil?
      errors.add(:order, "is not a valid order.")
    end
  end

  def finalize
    self[:unit_price] = unit_price
  end

end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
	has_many :orders
end

app/models/platform.rb
class Platform < ApplicationRecord
  has_many :products
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  belongs_to :platform
  has_many :order_items

  mount_uploaders :picture, PictureUploader
  serialize :picture, JSON
end

app/models/shipping.rb
class Shipping < ApplicationRecord
  has_many :orders
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_any!, only: [:show]
  before_action :authenticate_admin!, except: [:show, :new]
  before_action do
    permissions({index:'Zamówienia', edit:'Zamówienia', create:'Zamówienia', update:'Zamówienia', destroy:'Zamówienia'})
  end


  # before_action :authenticate_user!

  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.where.not(order_status: nil)
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    @order_items = OrderItem.where(order_id: @order.id)
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Nowe zamówienie zostało utworzone.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update

    StatusMailer.welcome_email(@order, params).deliver_now

    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Dane zamówienia zostały edytowane.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Zamówienie zostało usunięte.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:shipping_id, :order_status_id, :country, :city, :postal_code, :street)
    end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/amenities_helper.rb
module AmenitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def have(permision)
    current_admin.amenities.each do |a|
      if a == permision
        return true
      end
    end
    return false
  end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/platforms_helper.rb
module PlatformsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/shippings_helper.rb
module ShippingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/orders/_form.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <%= form_for order do |f| %>



        <div class="form-group">
          <%= f.label 'Nazwa' %>
          <%= f.collection_select :order_status_id, OrderStatus.all, :id, :name,{}, {class:'form-control'} %>
        </div>

        <div class="form-group">
          <%= check_box_tag 'form_dis' %>
          <%= label_tag 'label', 'Podaj dodatkowe informacje:', class: 'control-label' %>

        </div>

        <div class="form-group">
          <%= label_tag 'Dodatkowe informacje:' %>
          <%= text_area_tag 'info','', class:'form-control', placeholder: 'podaj info', disabled: 'disabled' %>
        </div>

        <div class="form-group">
          <%= f.submit 'Zapisz', class:'btn btn-primary btn-block'%>
        </div>
    <% end %>
  </div>
</div>


<script type="text/javascript" charset="utf-8">
    $('#form_dis').on('click', function(){
        if($(this).prop('checked')){
            $('#info').removeAttr('disabled');
        } else {
            $('#info').attr('disabled', 'disabled');
        }
    })
</script>

app/views/orders/edit.html.erb
<div class="row">
  <div class="col-md-12">
    <h1>Edytowanie Zamówienia</h1>

    <%= render 'form', order: @order %>

    <%= link_to 'Podgląd', @order, class: 'btn btn-default' %> |
    <%= link_to 'Wstecz', orders_path, class: 'btn btn-default' %>
  </div>
</div>

app/views/orders/index.html.erb
<div class="row">
  <div class="col-md-12">
    <h1>Zamówienia</h1>

    <table class="table table-bordered table-condensed table-striped">
      <thead>
      <tr>
        <th>Id</th>
        <th>Użytkownik</th>
        <th>Status</th>
        <th>Dostawa</th>
        <th>Stwożony</th>
        <th>Edytowany</th>
        <th>Adres</th>
        <th>Narzędzia</th>
      </tr>
      </thead>

      <tbody>
      <% @orders.each do |order| %>
        <tr>
          <td><%= order.id %></td>
          <td>
            <% if order.user %>
            (<%= order.user.id %>)<%= order.user.email %>
            <% end %>
          </td>
          <td>
            <% if order.order_status %>
              <%= order.order_status.name %>
            <% end %>
            </td>
          <td>
            <% if order.shipping %>
              <%= order.shipping.name %>
            <% end %>
          </td>
          <td><%= order.created_at %></td>
          <td><%= order.updated_at %></td>
          <td>
              <%= order.country %>, <%= order.city %>, <%= order.postal_code %>, <%= order.street %>
          </td>
          <td>
            <ul class="list-inline">
              <li>

                <%= link_to order do %>
                    <%= fa_icon 'eye', style: 'color: black' %> Podgląd
                <% end %>
              </li>
              <li>
                <%= link_to edit_order_path(order) do %>
                    <%= fa_icon 'pencil', style: 'color: black' %> Edycja
                <% end %>
              </li>
              <% if false %>
                  <li>
                    <%= link_to order, method: :delete, data: {confirm: 'Jesteś pewien?'} do %>
                        <%= fa_icon 'times', style: 'color: black' %> Usuń
                    <% end %>
                  </li>
              <% end %>
            </ul>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>

    <% if false %>
        <%= link_to new_order_path, class: 'btn btn-default' do %>
            <%= fa_icon('plus') %>  Nowe Zamówienie
        <% end %>
    <% end %>
  </div>
</div>

app/views/orders/new.html.erb
<div class="row">
  <div class="col-md-12">
    <h1>Nowe Zamówienie</h1>

    <%= render 'form', order: @order %>

    <%= link_to 'Wstecz', orders_path, class: 'btn btn-default' %>
  </div>
</div>

app/views/orders/show.html.erb
<div class="row">
  <div class="col-md-12">
    <table class="table table-bordered table-condensed table-striped">
      <thead>
      <tr>
        <% if admin_signed_in? %>
        <th>Id</th>
        <th>Użytkownik</th>
        <% end %>
        <th>Status</th>
        <th>Dostawa</th>
        <th>Stwożony</th>
        <th>Edytowany</th>
        <th>Adres</th>
      </tr>
      </thead>
      <tbody>
      <tr>
        <% if admin_signed_in? %>
        <td><%= @order.id %></td>
        <td>(<%= @order.user.id %>)<%= @order.user.email %></td>
        <% end %>
        <td><%= @order.order_status.name %></td>
        <td><%= @order.shipping.name %></td>
        <td><%= @order.created_at %></td>
        <td><%= @order.updated_at %></td>
        <td><%= @order.country %>, <%= @order.city %>, <%= @order.postal_code %>, <%= @order.street %> </td>
      </tr>
      </tbody>
    </table>

    <table class="table table-bordered table-condensed table-striped">
      <thead>
      <tr>
        <th>Obraz</th>
        <th>Produkt</th>
        <th>Cena</th>
        <th>Ilość</th>
        <th>Razem</th>
      </tr>
      </thead>
      <tbody>
      <% x=0 %>
      <% @order_items.each do |item| %>
          <% x+=item.unit_price*item.quantity %>
          <tr>
            <td>
              <% if item.product.picture %>
                  <%= image_tag(item.product.picture[0].url, class: 'table-pic') %>
              <% end %>
            </td>
            <td><%= item.product.name %></td>
            <td><%= sprintf "%0.02f", item.unit_price %> zł</td>
            <td><%= item.quantity %></td>
            <td><%= sprintf "%0.02f", item.unit_price*item.quantity %> zł</td>
          </tr>
      <% end %>
      </tbody>

      <tfoot>
      <tr>
        <td colspan="4">
          <p class="pull-right">Łącznie:</p>
        </td>
        <td>
          <%= sprintf "%0.02f", x %> zł
        </td>
      </tr>
      <tr>
        <td colspan="4">
          <p class="pull-right">Dostawa:</p>
        </td>
        <td>
          <p id="shipping_price">
            <%= sprintf "%0.02f", @order.shipping.price %> zł
          </p>
        </td>
      </tr>
      <tr>
        <td colspan="4">
          <p class="pull-right">Z dostawą:</p>
        </td>
        <td>
          <p id="total_and_shipping">
            <%= sprintf "%0.02f", x+@order.shipping.price %> zł
          </p>
        </td>
      </tr>
      </tfoot>

    </table>


    <% if false %>
        <%= link_to 'Edytuj', edit_order_path(@order), class: 'btn btn-default' %> |
    <% end %>

    <% if admin_signed_in? %>
        <%= link_to 'Wstecz', orders_path, class: 'btn btn-default' %>
    <% else %>
        <%= link_to 'Wstecz', current_user, class: 'btn btn-default' %>
    <% end %>
  </div>
</div>