config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'products#index'


  devise_for :admins
  devise_for :users



  resources :amenities

  get 'carts/order'
  post 'carts/finalize'
  resource :carts, only: [:show]

  resources :categories

  resources :order_items, only: [:create, :update, :destroy]

  resources :orders

  resources :platforms

  get 'products/shop'
  resources :products

  resources :shippings

  get 'users/:id/edit_address', to: 'users#edit_address', as: 'users_edit_address'
  resources :users
  resources :admins


end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_confirmation_of :password
  serialize :amenities, JSON
end

app/models/amenity.rb
class Amenity < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :products
end

app/models/order.rb
class Order < ApplicationRecord

  has_many :order_items
  before_create :set_order_params
  belongs_to :shipping, optional: true
  belongs_to :order_status, optional: true
  belongs_to :user, optional: true

private

  def set_order_params
    # self.order_status_id = OrderStatus.find_by(name: 'Stan tymczasowy').id
    # self.shipping_id = Shipping.find_by(name: 'Stan tymczasowy').id
  end

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :product_present
  validate :order_present

  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price-(product.price*(product.discount.to_f / 100 ))
    end
  end

private
  def product_present
    if product.nil?
      errors.add(:product, "is not valid or is not active.")
    end
  end

  def order_present
    if order.nil?
      errors.add(:order, "is not a valid order.")
    end
  end

  def finalize
    self[:unit_price] = unit_price
  end

end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
	has_many :orders
end

app/models/platform.rb
class Platform < ApplicationRecord
  has_many :products
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  belongs_to :platform
  has_many :order_items

  mount_uploaders :picture, PictureUploader
  serialize :picture, JSON
end

app/models/shipping.rb
class Shipping < ApplicationRecord
  has_many :orders
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!, only: [:finalize]

  def show
    @order_items = current_order.order_items
  end

  def order
    @order_items = current_order.order_items
  end
  
  def finalize
    params[:order][:order_status_id] = 1
    params[:order][:user_id] = current_user.id

    if params[:form_dis].nil?
      params[:order][:country] = current_user.country
      params[:order][:city] = current_user.city
      params[:order][:postal_code] = current_user.postal_code
      params[:order][:street] = current_user.street
    end

    current_order.order_items.each do |item|
      item.product.update_attributes(stock: item.product.stock-item.quantity)
    end

    Order.find(current_order.id).update_attributes(cart_params)
    session.delete(:order_id)
    redirect_to root_path

  end

  private
  def cart_params
    # :order_status_id, :user, :country, :city, :postal_code, :street, :form_dis, shipping: [:shipping_id]
    params.require(:order).permit(:country, :city, :postal_code, :street, :order_status_id, :shipping_id, :user_id)
  end

end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/amenities_helper.rb
module AmenitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def have(permision)
    current_admin.amenities.each do |a|
      if a == permision
        return true
      end
    end
    return false
  end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/platforms_helper.rb
module PlatformsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/shippings_helper.rb
module ShippingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carts/_cart_row.html.erb
<div class="well">

  <div class="row">
    <div class="col-xs-2">
      <h4><%= product.name %></h4>
    </div>
    <div class="col-xs-2">
      <p><%= image_tag(product.picture[0].url, class: 'pic') %></p>
    </div>
    <div class="col-xs-5">
      <p><%= product.description %></p>
    </div>
    <div class="col-xs-3">
      <%= form_for order_item, remote: true do |f| %>
        <h4 class="text-right">Cena: <span style="color: green"><%= sprintf "%0.02f", order_item.unit_price%>zł</span></h4>
          <div class="text-right">
            <div class="input-group">
            <%= f.number_field :quantity, value: order_item.quantity.to_i, class: "form-control", min: 1 %>
            <%= f.hidden_field :product_id, value: product.id %>
            <div class="input-group-btn">
              <%= f.submit 'Zmień ilość', class: "btn btn-primary" %>
              <%= link_to  order_item, { data: { confirm: "Czy jesteś pewien że chcesz usunąć '#{order_item.product.name}' z koszyka?" }, method: :delete, remote: true, class: "btn btn-danger" } do %>
                  <%= fa_icon('times') %> Usuń
              <% end %>
            </div>
            </div>
          </div>

        <h4 class="text-right">Łącznie: <span style="color: green">
        <%=
          sprintf "%0.02f", order_item.unit_price*order_item.quantity
          %>zł

        </span></h4>
      <% end %>
    </div>

  </div>
</div>

app/views/carts/_shopping_cart.html.erb
<% if !@order_item.nil? && @order_item.errors.any? %>
  <div class="alert alert-danger">
    <ul>
    <% @order_item.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<% if @order_items.size == 0 %>
  <p class="text-center">
    Koszyk jest pusty. Wróć do listy <%= link_to "listy produktów", products_path %> i dodaj produkty do koszyka.
  </p>
<% else %>
  <% @order_items.each do |order_item| %>
    <%= render 'carts/cart_row', product: order_item.product, order_item: order_item, show_total: true %>
  <% end %>
  <%= link_to 'Podsumowanie', carts_order_path, class: "btn btn-primary pull-right"  %>
<% end %>

app/views/carts/order.html.erb
<div class="row">
  <div class="col-md-12 ">
    <table class="table table-bordered table-condensed table-striped">
      <thead>
      <tr>
        <th>Obraz</th>
        <th>Nazwa</th>
        <th>Opis</th>
        <th>Kategoria</th>
        <th>Platforma</th>
        <th>Cena</th>
        <th>Ilość</th>
        <th>Łącznie</th>
      </tr>
      </thead>
      <tbody>
      <% x=0 %>
      <% @order_items.each do |order_item| %>
          <% x+=order_item.unit_price*order_item.quantity %>
        <tr>
          <td><%= image_tag(order_item.product.picture[0].url, class: 'table-pic') %></td>
          <td><%= order_item.product.name %></td>
          <td><%= order_item.product.description %></td>
          <td><%= order_item.product.category.name %></td>
          <td>
            <%= order_item.product.platform.name %>
          </td>
          <td><%= sprintf "%0.02f", order_item.unit_price %> zł</td>
          <td><%= order_item.quantity %></td>
          <td><%= sprintf "%0.02f", order_item.unit_price*order_item.quantity %> zł</td>
        </tr>
      <% end %>
      </tbody>
      <tfoot>
      <tr>
        <td colspan="7">
          <p class="pull-right">Łącznie:</p>
        </td>
        <td>
          <%= sprintf "%0.02f", x %> zł
        </td>
      </tr>
      <tr>
        <td colspan="7">
          <p class="pull-right">Dostawa:</p>
        </td>
        <td>
          <p id="shipping_price">
            Wybierz rodzaj dostawy
          </p>
        </td>
      </tr>
      <tr>
        <td colspan="7">
          <p class="pull-right">Z dostawą:</p>
        </td>
        <td>
          <p id="total_and_shipping">
            Wybierz rodzaj dostawy
          </p>
        </td>
      </tr>
      </tfoot>

    </table>
  </div>
</div>
<div class="row">
  <div class="col-md-12 ">
    <% if signed_in? %>
      <% if current_user.country.blank? or current_user.city.blank? or current_user.postal_code.blank? or current_user.street.blank? %>
            <p>Aby zrealizować zamówienie muisz uzupełnić swój <%= link_to 'adres', users_edit_address_path(current_user.id) %></p>
      <% else %>
        <%= form_tag carts_finalize_path do %>
          <div class="form-group">
            <%= check_box_tag 'form_dis' %>
            <%= label_tag 'label', 'Zmień adres dostawy',class: 'control-label' %>
          </div>
          <div class="form-group col-md-6">
            <%= label_tag 'label', 'Kraj',class: 'control-label' %>
            <%= text_field_tag 'order[country]', current_user.country, class: 'form-control', disabled: 'disabled' %>
          </div>
          <div class="form-group col-md-6">
            <%= label_tag 'label', 'Miasto',class: 'control-label' %>
            <%= text_field_tag 'order[city]', current_user.city, class: 'form-control', disabled: 'disabled' %>
          </div>
          <div class="form-group col-md-6">
            <%= label_tag 'label', 'Kod pocztowy',class: 'control-label' %>
            <%= text_field_tag 'order[postal_code]', current_user.postal_code, class: 'form-control', disabled: 'disabled'%>
          </div>
          <div class="form-group col-md-6">
            <%= label_tag 'label', 'Ulica',class: 'control-label' %>
            <%= text_field_tag 'order[street]', current_user.street, class: 'form-control', disabled: 'disabled' %>
          </div>
          <div class="form-group">
            <%= label_tag 'label', 'Wybierz rodzaj dostawy',class: 'control-label' %>
            <%= collection_select :order,
                                  :shipping_id,
                                  Shipping.all.collect { |t| [ t.id, "#{t.name}(#{sprintf "%0.02f", t.price} zł)" ] },
                                  :first,
                                  :last,
                                  {},
                                  {class: 'form-control'}
            %>
          </div>
          <div class="form-group">
            <div class="form-group-btn">
              <%= submit_tag 'Zamów', class: 'btn btn-primary' %>
            </div>
          </div>
        <% end %>
      <% end %>
    <% else %>
        <p>Aby zrealizować zamówienie muisz się <%= link_to 'zalogować', new_user_session_path %></p>
    <% end %>
  </div>
</div>

<script type="text/javascript" charset="utf-8">
$('#form_dis').on('click', function(){
  if($(this).prop('checked')){
    $('#order_country').removeAttr('disabled');
    $('#order_city').removeAttr('disabled');
    $('#order_postal_code').removeAttr('disabled');
    $('#order_street').removeAttr('disabled');
  } else {
    $('#order_country').attr('disabled', 'disabled');
    $('#order_city').attr('disabled', 'disabled');
    $('#order_postal_code').attr('disabled', 'disabled');
    $('#order_street').attr('disabled', 'disabled');
  }
})
</script>

<script type="text/javascript" charset="utf-8">
    var patt = /\(((\d+).+)\)/;
  document.getElementById("order_shipping_id").onchange = function(){
    var e = document.getElementById("order_shipping_id");
    var str = e.options[e.selectedIndex].text;
    str = str.match(patt)[1];
    document.getElementById("shipping_price").innerHTML = str;
    document.getElementById("total_and_shipping").innerHTML = String(parseInt(str)+<%= sprintf "%0.02f", x %>)+'zł';
  }
</script>

app/views/carts/show.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="shopping-cart">
      <%= render "shopping_cart" %>
    </div>
  </div>
</div>