config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'products#index'


  devise_for :admins
  devise_for :users



  resources :amenities

  get 'carts/order'
  post 'carts/finalize'
  resource :carts, only: [:show]

  resources :categories

  resources :order_items, only: [:create, :update, :destroy]

  resources :orders

  resources :platforms

  get 'products/shop'
  resources :products

  resources :shippings

  get 'users/:id/edit_address', to: 'users#edit_address', as: 'users_edit_address'
  resources :users
  resources :admins


end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_confirmation_of :password
  serialize :amenities, JSON
end

app/models/amenity.rb
class Amenity < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :products
end

app/models/order.rb
class Order < ApplicationRecord

  has_many :order_items
  before_create :set_order_params
  belongs_to :shipping, optional: true
  belongs_to :order_status, optional: true
  belongs_to :user, optional: true

private

  def set_order_params
    # self.order_status_id = OrderStatus.find_by(name: 'Stan tymczasowy').id
    # self.shipping_id = Shipping.find_by(name: 'Stan tymczasowy').id
  end

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :product_present
  validate :order_present

  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price-(product.price*(product.discount.to_f / 100 ))
    end
  end

private
  def product_present
    if product.nil?
      errors.add(:product, "is not valid or is not active.")
    end
  end

  def order_present
    if order.nil?
      errors.add(:order, "is not a valid order.")
    end
  end

  def finalize
    self[:unit_price] = unit_price
  end

end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
	has_many :orders
end

app/models/platform.rb
class Platform < ApplicationRecord
  has_many :products
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  belongs_to :platform
  has_many :order_items

  mount_uploaders :picture, PictureUploader
  serialize :picture, JSON
end

app/models/shipping.rb
class Shipping < ApplicationRecord
  has_many :orders
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_admin!, except: [:index]
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action do
    permissions({index:'Magazyn', show:'Magazyn', new:'Magazyn', edit:'Magazyn', create:'Magazyn', update:'Magazyn', destroy:'Magazyn'})
  end

  # GET /products
  # GET /products.json

  def index
    @products = Product.all
    if params[:filter]
      p = search_params
      @products = @products.where(category_id: p[:category_id]) unless p[:category_id].blank?
      @products = @products.where(platform_id: p[:platform_id]) unless p[:platform_id].blank?
      @products = @products.where("discount >= #{p[:discount_min]}") unless p[:discount_min].blank?
      @products = @products.where("discount <= #{p[:discount_max]}") unless p[:discount_max].blank?
    end

    @order_item = current_order.order_items.new
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create

    @product = Product.new(product_params)
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Nowy produkt został utworzony.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Dane produktu zostały edytowane.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Produkt został usunięty.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :stock, :category_id, :price, {picture: []}, :platform_id, :fil_cat, :fil_plat, :discount)
    end

  def search_params
    params.
        # Optionally, whitelist your search parameters with permit
        require(:filter).permit(:platform_id,:category_id,:discount_min,:discount_max).
        # Delete any passed params that are nil or empty string
        delete_if {|key, value| value.blank? }
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/amenities_helper.rb
module AmenitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def have(permision)
    current_admin.amenities.each do |a|
      if a == permision
        return true
      end
    end
    return false
  end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/platforms_helper.rb
module PlatformsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/shippings_helper.rb
module ShippingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/products/_filter.html.erb
<div class="row">
  <div class="col-md-12">
    <%= form_tag products_path, method: 'get', enforce_utf8: false, class:'form-inline' do %>
        <fieldset>
          <legend>Filtrowanie:</legend>
          <div class="form-group">
            <%= label_tag(:category_id, 'Kategoria:') %>
            <%= collection_select(:filter, :category_id, Category.all, :id, :name, {:include_blank => 'wybierz'}, {class: 'form-control'}) %>
          </div>
          <div class="form-group">
            <%= label_tag(:platform_id, 'Platforma:') %>
            <%= collection_select(:filter, :platform_id, Platform.all, :id, :name, {:include_blank => 'wybierz'}, {class: 'form-control'}) %>
          </div> <%= label_tag(:platform_id, 'Obniżka(%):') %>
          <div class="form-group">

            <%= number_field_tag 'filter[discount_min]', nil, step: "1", min: 0, max:100, placeholder: 'min', class: 'form-control'%>
          </div> -
          <div class="form-group">
            <%= number_field_tag 'filter[discount_max]', nil, step: "1", min: 0, max:100, placeholder: 'max', class:'form-control' %>
          </div>
          <div class="form-group">
            <%= submit_tag 'Filtruj', name: nil, class: 'btn btn-default' %>
          </div>
        </fieldset>
    <% end %>
  </div>
</div>

<% if params[:filter] %>
  <script type="text/javascript" charset="utf-8">
      $(window).load(function() {
          $('#filter_category_id').val(<%= params[:filter][:category_id] %>);
          $('#filter_platform_id').val(<%= params[:filter][:platform_id] %>);
          $('#filter_discount_min').val(<%= params[:filter][:discount_min] %>);
          $('#filter_discount_max').val(<%= params[:filter][:discount_max] %>);
      });
  </script>
<% end %>

app/views/products/_form.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <%= form_for(product) do |f| %>

        <div class="form-group">
          <%= f.label 'Nazwa' %>
          <%= f.text_field :name, class:'form-control', placeholder: 'podaj nazwę produktu' %>
        </div>

        <div class="form-group">
          <%= f.label 'Opis' %>
          <%= f.text_area :description, class:'form-control', placeholder: 'podaj opis produktu' %>
        </div>

        <div class="form-group">
          <%= f.label 'Ilość produktów w magazynie' %>
          <%= f.number_field :stock, class:'form-control', placeholder: 'podaj ilość produktów w magazynie' %>
        </div>

        <div class="form-group">
          <%= f.label 'Kategoria' %>
          <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class: 'form-control'}) %>
        </div>

        <div class="form-group">
          <%= f.label 'Platforma' %>
          <%= f.collection_select(:platform_id, Platform.all, :id, :name, {}, {class: 'form-control'}) %>
        </div>

        <div class="form-group">
          <%= f.label 'Cena' %>
          <%= f.number_field :price, class:'form-control', step: "0.01", placeholder: 'podaj cenę' %>
        </div>

        <div class="form-group">
          <%= f.label 'Obniżka(%)' %>
          <%= f.number_field :discount, class:'form-control', step: "1", min: 0, max:100, placeholder: 'podaj wysokość obniżki w %' %>
        </div>

        <div class="form-group">
          <%= f.label 'Obraz' %>
          <%= f.file_field :picture, multiple: true %>
        </div>

        <div class="form-group">
          <%= f.submit 'Zapisz', class:'btn btn-primary btn-block' %>
        </div>
    <% end %>
  </div>
</div>

app/views/products/_product_row.html.erb
<div class="well">

  <div class="row">
    <div class="col-xs-2">
      <h4><%= product.name %></h4>
    </div>
    <% if product.picture %>
        <div class="col-xs-2">
          <p>
          <% if product.picture[0] %>
            <%= link_to product.picture[0].url, data:{fancybox:"gallery#{product.id}"} do %>
                <%= image_tag(product.picture[0].url, class: 'pic') %>
            <% end %>

          </p>
          <% product.picture[1..-1].each do |p|%>
              <%= link_to p.url, data:{fancybox:"gallery#{product.id}"}, hidden: true do %>
                  <%= image_tag(p.url, class: 'pic') %>
              <% end %>
          <% end %>
          <% end %>
        </div>
    <% end %>
    <div class="col-xs-5">
      <p><%= product.description %></p>
    </div>
    <div class="col-xs-3">
      <%= form_for order_item, remote: true do |f| %>

      <% if !product.discount.blank? %>
            <h4 class="text-right">
              <span class="label text-right label-danger"><%= "#{product.discount}%" %></span>
              <del>Cena: <span style="color: green"><%= sprintf "%0.02f", product.price %>zł</span></del>
            </h4>
        <h4 class="text-right">Cena: <span style="color: red"><%=  sprintf "%0.02f", product.price-(product.price*(product.discount.to_f / 100 ))%>zł</span></h4>
      <% else %>
          <h4 class="text-right">Cena: <span style="color: green"><%= sprintf "%0.02f",product.price %>zł</span></h4>
      <% end %>

        <div class="input-group">
          <%= f.number_field :quantity, value: 1, class: "form-control", min: 1, max: product.stock %>
          <div class="input-group-btn">
            <%= f.hidden_field :product_id, value: product.id %>
            <%= button_tag type: "Dodaj", class: "btn btn-primary", disabled: product.stock == 0 do %>
                Dodaj <%= fa_icon('cart-plus') %>
            <% end %>
          </div>
        </div>

      <% end %>
    </div>

  </div>
</div>

app/views/products/edit.html.erb
<div class="row">
  <div class="col-md-12">
    <h1>Edytowanie Produktu</h1>

    <%= render 'form', product: @product %>

    <%= link_to 'Podgląd', @product, class: 'btn btn-default' %> |
    <%= link_to 'Wstecz', products_path, class: 'btn btn-default' %>
  </div>
</div>

app/views/products/index.html.erb

<%= render "filter" %>

<div class="row">
  <div class="col-md-12">
    <h1>Produkty</h1>
    <% if admin_signed_in? %>
      <table class="table table-bordered table-condensed table-striped">
        <thead>
        <tr>
          <th>Obraz</th>
          <th>Nazwa</th>
          <th>Opis</th>
          <th>Kategoria</th>
          <th>Platforma</th>
          <th>Stan Magazynowy</th>
          <th>Cena</th>
          <th>Obniżka</th>
          <th>Narzędzia</th>
        </tr>
        </thead>

        <tbody>
        <% @products.each do |product| %>
            <tr>
              <td>
                <% if product.picture[0] %>
                    <%= image_tag(product.picture[0].url, class: 'table-pic') %>
                <% end %>
              </td>
              <td><%= product.name %></td>
              <td><%= product.description %></td>
              <td><%= product.category.name %></td>

              <td>
                <%= product.platform.name %>
              </td>

              <td><%= product.stock %></td>
              <td><%= sprintf "%0.02f", product.price %>zł</td>
              <td>
                <% if !product.discount.blank? %>
                    <div style="color: red"><%= product.discount %>%</div>
                <% else %>
                    <div>0%</div>
                <% end %>
              </td>
              <td>
                <ul class="list-inline">
                  <li>
                    <%= link_to product do %>
                        <%= fa_icon 'eye', style: 'color: black' %> Podgląd
                    <% end %>
                  </li>

                  <li>
                    <%= link_to edit_product_path product do %>
                        <%= fa_icon 'pencil', style: 'color: black' %> Edycja
                    <% end %>
                  </li>

                  <li>
                    <%= link_to product, method: :delete, data: {confirm: 'Jesteś pewien?'} do %>
                        <%= fa_icon 'times', style: 'color: black' %> Usuń
                    <% end %>
                  </li>
                </ul>
              </td>

            </tr>
        <% end %>
        </tbody>
      </table>

        <%= link_to new_product_path, class: 'btn btn-default' do %>
            <%= fa_icon('plus') %>  Nowy Produkt
        <% end %>

    <% else %>
        <div class="row">
          <div class="col-xs-12">
            <% @products.each do |product| %>
                <%= render "product_row", product: product, order_item: @order_item %>
            <% end %>
          </div>
        </div>
    <% end %>
  </div>
</div>

app/views/products/new.html.erb
<div class="row">
  <div class="col-md-12">
    <h1>Nowy produkt</h1>

    <%= render 'form', product: @product %>

    <%= link_to 'Wstecz', products_path, class: 'btn btn-default' %>
  </div>
</div>

app/views/products/shop.html.erb

<%= render "filter" %>

<div class="row">
  <h1>Products</h1>

      <h3 class="text-center">Products for Sale</h3>

      <div class="row">
        <div class="col-xs-10 col-xs-offset-1">
          <% @products.each do |product| %>
              <%= render "product_row", product: product, order_item: @order_item %>
          <% end %>
        </div>
      </div>

</div>

app/views/products/show.html.erb
<div class="row">
  <div class="col-md-12">
    <p>
    <strong>Name:</strong>
    <%= @product.name %>
  </p>

    <p>
      <strong>Description:</strong>
      <%= @product.description %>
    </p>

    <p>
      <strong>Stock:</strong>
      <%= @product.stock %>
    </p>

    <p>
      <strong>Category:</strong>
      <%= @product.category.name %>
    </p>

    <p>
      <strong>Price:</strong>
      <%= @product.price %>
    </p>

    <%= link_to 'Edytuj', edit_product_path(@product), class: 'btn btn-default' %> |
    <%= link_to 'Wstecz', products_path, class: 'btn btn-default' %>
  </div>
</div>